<a href="https://colab.research.google.com/github/murali-marimekala/tensorflow_deeplearning_bootcamp/blob/main/6_tf_manipulating_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.17.1


In [2]:
#Basic operations
# Use addition operator
tensor = tf.constant([[1,2],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [3]:
#Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [4]:
#if you want to original tensor
tensor = tensor + 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [5]:
#Multiplicatiot
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[110, 120],
       [130, 140]], dtype=int32)>

In [6]:
#subtraction
tensor = tensor - 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [7]:
#We can use the tensorflow build in function
tf.multiply(tensor,10)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [8]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [9]:
a = tf.constant(10)
b = tf.constant(20)
a
b

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [10]:
result1 = tf.add(a,b)
result2 = tf.multiply(a,b)
result3 = tf.subtract(a,b)
result4 = tf.divide(a,b)

In [11]:
result1

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [12]:
result2

<tf.Tensor: shape=(), dtype=int32, numpy=200>

In [13]:
result3

<tf.Tensor: shape=(), dtype=int32, numpy=-10>

In [41]:
result4

<tf.Tensor: shape=(), dtype=float64, numpy=0.5>

In [14]:
#Matrix Multiplication with Tensors
tensor1 = tf.constant([[1,2],[3,4]])
tensor2 = tf.constant([[5,6],[7,8]])
tf.matmul(tensor1,tensor2) #tf.linalg.mul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]], dtype=int32)>

In [ ]:
# Try website matrixmultiplication.xyz

In [15]:
print(tf.matmul(tensor1,tensor2))

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [16]:
#Matridx multiplication with python operator "@"
tensor1 @ tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]], dtype=int32)>

In [17]:
#above is not same like multiplication
tensor1 * tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]], dtype=int32)>

In [18]:
#Create a tensor (3, 2) tensor
x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

#Create another tensor (3,2)
y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

#Multiply the two tensors of same shape
tf.matmul(x, y)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [19]:
#Create a tensor (3, 2) tensor
x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

#Create another tensor (3,2)
y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

#Multiply the two tensors of same shape
x*y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 16],
       [27, 40],
       [55, 72]], dtype=int32)>

https://www.mathsisfun.com/algebra/

#Two rules of Matrix Multiplication
1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions

In [21]:
#Lets change the shape of Y
tf.reshape(y,shape=(2,3))
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [22]:
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [28]:
tf.reshape(y, shape=(2,3))


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [25]:
tf.matmul(x,tf.reshape(y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [26]:
tf.matmul(tf.reshape(x,shape=(2,3)),y) #Chaning the shape of x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [30]:
tf.reshape(x,shape=(2,3)).shape,y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [33]:

#Can do the same with transpose
x, tf.transpose(x), tf.transpose(x).shape

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 TensorShape([2, 3]))

In [35]:
#Try matrix multiplication rather than reshape
tf.matmul(tf.transpose(x),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>