<a href="https://colab.research.google.com/github/murali-marimekala/tensorflow_deeplearning_bootcamp/blob/main/6_tf_manipulating_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import tensorflow as tf
print(tf.__version__)

2.17.1


In [28]:
#Basic operations
# Use addition operator
tensor = tf.constant([[1,2],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [29]:
#Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [30]:
#if you want to original tensor
tensor = tensor + 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [31]:
#Multiplicatiot
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[110, 120],
       [130, 140]], dtype=int32)>

In [32]:
#subtraction
tensor = tensor - 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [33]:
#We can use the tensorflow build in function
tf.multiply(tensor,10)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [34]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [36]:
a = tf.constant(10)
b = tf.constant(20)
a
b

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [37]:
result1 = tf.add(a,b)
result2 = tf.multiply(a,b)
result3 = tf.subtract(a,b)
result4 = tf.divide(a,b)

<tf.Tensor: shape=(), dtype=float64, numpy=0.5>

In [38]:
result1

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [39]:
result2

<tf.Tensor: shape=(), dtype=int32, numpy=200>

In [40]:
result3

<tf.Tensor: shape=(), dtype=int32, numpy=-10>

In [41]:
result4

<tf.Tensor: shape=(), dtype=float64, numpy=0.5>