<a href="https://colab.research.google.com/github/murali-marimekala/tensorflow_deeplearning_bootcamp/blob/main/7_Aggregating_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.17.1


Aggregation Tensors

In [3]:
#Aggregating tensors = condensing them from multiple values down to a smaller amount of values

#Getting the absolute values

D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [5]:
#Get absolute vlaues
tf. abs(D)


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [7]:
#Lets go through the following form of aggregation
#Get the maximum and minimum
#Get the mean and sum of sensor

max = tf.reduce_max(D)
min = tf.reduce_min(D)

max, min

(<tf.Tensor: shape=(), dtype=int32, numpy=-7>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-10>)

In [9]:
import numpy as np
E = tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([67, 69, 60, 91, 79, 51, 94,  6, 52, 70, 56, 79, 11, 51, 73, 90, 43,
        2, 18, 64, 90, 99, 43, 61, 47, 17, 74, 41, 49, 81, 30, 97, 17, 86,
       33, 13, 87, 59, 89, 62, 29, 21, 56, 52, 82, 77, 11, 34, 52, 38])>

In [10]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [13]:
tf.reduce_min(E), tf.reduce_max(E)

(<tf.Tensor: shape=(), dtype=int64, numpy=2>,
 <tf.Tensor: shape=(), dtype=int64, numpy=99>)

In [14]:
#Get mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=55>

In [15]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2753>

In [16]:
#find the variance : We need access to tensorflow probability
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=720>

In [18]:
#Standard deviation
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=26.842064>