<a href="https://colab.research.google.com/github/murali-marimekala/tensorflow_deeplearning_bootcamp/blob/main/7_Aggregating_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.17.1


Aggregation Tensors

In [3]:
#Aggregating tensors = condensing them from multiple values down to a smaller amount of values

#Getting the absolute values

D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [5]:
#Get absolute vlaues
tf. abs(D)


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [7]:
#Lets go through the following form of aggregation
#Get the maximum and minimum
#Get the mean and sum of sensor

max = tf.reduce_max(D)
min = tf.reduce_min(D)

max, min

(<tf.Tensor: shape=(), dtype=int32, numpy=-7>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-10>)

In [9]:
import numpy as np
E = tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([67, 69, 60, 91, 79, 51, 94,  6, 52, 70, 56, 79, 11, 51, 73, 90, 43,
        2, 18, 64, 90, 99, 43, 61, 47, 17, 74, 41, 49, 81, 30, 97, 17, 86,
       33, 13, 87, 59, 89, 62, 29, 21, 56, 52, 82, 77, 11, 34, 52, 38])>

In [10]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [13]:
tf.reduce_min(E), tf.reduce_max(E)

(<tf.Tensor: shape=(), dtype=int64, numpy=2>,
 <tf.Tensor: shape=(), dtype=int64, numpy=99>)

In [14]:
#Get mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=55>

In [15]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2753>

In [16]:
#find the variance : We need access to tensorflow probability
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=720>

In [18]:
#Standard deviation
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=26.842064>

In [19]:
#finding variance in different way
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=720.4964>

In [35]:
#Find the positional max and min : At which index max or min occurs in a tensor
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [36]:
#Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [37]:
#Index on our larget value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [39]:
#Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [40]:
#Find the min value of F
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [41]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [43]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>