<a href="https://colab.research.google.com/github/murali-marimekala/tensorflow_deeplearning_bootcamp/blob/main/1_tf_constant.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Fundamental concepts of tensors are covered using tensorflow

#Topics covered
#1. Introduction to tensors
    #1.1 Scalar  :Single number
    #1.2 Vector  : A number with direction
    #1.3 Matrix  : Two dimensional array of number
    #1.3 Matrix with different dtype
    #1.4 Tensor : N dimensional array of number. Where n can be any number.
#2. Getting information from tensors
#3. Manipulating tensors
#4. Tensors & Numpy
#5. Using @tf.function (a way to speed up your regular python functions)
#6. Using GPU with Tensors flow (or TPUs)


In [3]:
#Introduction to tensors

#import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.17.1


In [4]:
#Creating tensors with tf.constant()
scalar = tf.constant(7) #create a tensor from tensor-like object
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
#check number of dimensions of scalar tensor
scalar.ndim

0

In [6]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
vector.ndim

1

In [8]:
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
matrix.ndim


2

In [12]:
#Create another matrix
another_matrix = tf.constant([[10.,7.],
                             [3.,2.],
                             [8.,9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [19]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [20]:
another_matrix.shape

TensorShape([3, 2])

In [21]:
#Number of dimensions of other matrix
another_matrix.ndim

2

In [27]:
#Creating another tensor
tensor = tf.constant([[[ 1, 2, 3],
                       [ 4, 5, 6]],

                      [[ 7, 8, 9],
                       [ 10, 11, 12]],

                      [[ 13, 14, 15],
                       [ 16, 17, 18]]], dtype=tf.int32)

In [29]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [24]:
tensor.ndim

3