<a href="https://colab.research.google.com/github/murali-marimekala/tensorflow_deeplearning_bootcamp/blob/main/3_tf_random_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.17.1


In [7]:
#create two random tensors
random_1 = tf.random.Generator.from_seed(7)
random_1 = random_1.normal(shape=(3,2))
print(random_1)
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
print(random_2)

#Check if they are equal. Tweak the from_seed(value)  value and observe the
#difference
random_1, random_2, random_1 == random_2

tf.Tensor(
[[-1.3240396   0.28785667]
 [-0.8757901  -0.08857018]
 [ 0.69211644  0.84215707]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [ ]:
#Shuffle the order of elements in a tensor