<a href="https://colab.research.google.com/github/murali-marimekala/tensorflow_deeplearning_bootcamp/blob/main/6_tf_manipulating_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
print(tf.__version__)

2.17.1


In [3]:
#Basic operations
# Use addition operator
tensor = tf.constant([[1,2],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [4]:
#Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [5]:
#if you want to original tensor
tensor = tensor + 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [6]:
#Multiplicatiot
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[110, 120],
       [130, 140]], dtype=int32)>

In [7]:
#subtraction
tensor = tensor - 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [8]:
#We can use the tensorflow build in function
tf.multiply(tensor,10)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [9]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [10]:
a = tf.constant(10)
b = tf.constant(20)
a
b

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [11]:
result1 = tf.add(a,b)
result2 = tf.multiply(a,b)
result3 = tf.subtract(a,b)
result4 = tf.divide(a,b)

In [12]:
result1

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [13]:
result2

<tf.Tensor: shape=(), dtype=int32, numpy=200>

In [14]:
result3

<tf.Tensor: shape=(), dtype=int32, numpy=-10>

In [15]:
result4

<tf.Tensor: shape=(), dtype=float64, numpy=0.5>

In [16]:
#Matrix Multiplication with Tensors
tensor1 = tf.constant([[1,2],[3,4]])
tensor2 = tf.constant([[5,6],[7,8]])
tf.matmul(tensor1,tensor2) #tf.linalg.mul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]], dtype=int32)>

In [17]:
# Try website matrixmultiplication.xyz

In [18]:
print(tf.matmul(tensor1,tensor2))

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [19]:
#Matridx multiplication with python operator "@"
tensor1 @ tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]], dtype=int32)>

In [20]:
#above is not same like multiplication
tensor1 * tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]], dtype=int32)>

In [21]:
#Create a tensor (3, 2) tensor
x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

#Create another tensor (3,2)
y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

#Multiply the two tensors of same shape
tf.matmul(x, y)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [23]:
#Create a tensor (3, 2) tensor
x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

#Create another tensor (3,2)
y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

#Multiply the two tensors of same shape
x*y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 16],
       [27, 40],
       [55, 72]], dtype=int32)>

https://www.mathsisfun.com/algebra/

#Two rules of Matrix Multiplication
1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions

In [24]:
#Lets change the shape of Y
tf.reshape(y,shape=(2,3))
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [25]:
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [26]:
tf.reshape(y, shape=(2,3))


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [27]:
tf.matmul(x,tf.reshape(y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [28]:
tf.matmul(tf.reshape(x,shape=(2,3)),y) #Chaning the shape of x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [29]:
tf.reshape(x,shape=(2,3)).shape,y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [30]:

#Can do the same with transpose
x, tf.transpose(x), tf.transpose(x).shape

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 TensorShape([2, 3]))

In [31]:
#Try matrix multiplication rather than reshape
tf.matmul(tf.transpose(x),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [32]:
#Change data type of a tensor
#Create a  new tensor with default datatype (float32)

B= tf.constant([1.7,7.4])
B.dtype

tf.float32

In [35]:
B = tf.constant([7,10])
B.dtype

tf.int32

In [37]:
#Change from float32 to float16 (reduced precision)
D = tf.cast(B,dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

In [38]:
E = tf.cast(B,dtype=tf.int16)
E

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([ 7, 10], dtype=int16)>

In [39]:
#Change from int32 to float32
E = tf.cast(B, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [41]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>