<a href="https://colab.research.google.com/github/murali-marimekala/tensorflow_deeplearning_bootcamp/blob/main/8_Squeezing_the_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
print(tf.__version__)

2.17.1


In [3]:
#Create a tensor to get started
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.66032684, 0.9688436 , 0.00560045, 0.47016287, 0.02333736,
           0.5260854 , 0.1834768 , 0.8328866 , 0.7456157 , 0.26300955,
           0.17518663, 0.5613501 , 0.9907279 , 0.96482635, 0.31680965,
           0.46917784, 0.7230216 , 0.23586535, 0.8962258 , 0.405015  ,
           0.6650983 , 0.4595703 , 0.3455547 , 0.80536854, 0.1003772 ,
           0.21455538, 0.04263783, 0.35412812, 0.69675195, 0.23522878,
           0.1289227 , 0.02972865, 0.5633323 , 0.11741567, 0.6702889 ,
           0.3188572 , 0.6094867 , 0.63783383, 0.36138773, 0.6953902 ,
           0.6803795 , 0.7551242 , 0.14971662, 0.8068533 , 0.9675727 ,
           0.94682086, 0.54353714, 0.54715407, 0.48426998, 0.15358555]]]]],
      dtype=float32)>

In [4]:
G.shape


TensorShape([1, 1, 1, 1, 50])

In [5]:
G_Squeezed = tf.squeeze(G)
G_Squeezed,G_Squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.66032684, 0.9688436 , 0.00560045, 0.47016287, 0.02333736,
        0.5260854 , 0.1834768 , 0.8328866 , 0.7456157 , 0.26300955,
        0.17518663, 0.5613501 , 0.9907279 , 0.96482635, 0.31680965,
        0.46917784, 0.7230216 , 0.23586535, 0.8962258 , 0.405015  ,
        0.6650983 , 0.4595703 , 0.3455547 , 0.80536854, 0.1003772 ,
        0.21455538, 0.04263783, 0.35412812, 0.69675195, 0.23522878,
        0.1289227 , 0.02972865, 0.5633323 , 0.11741567, 0.6702889 ,
        0.3188572 , 0.6094867 , 0.63783383, 0.36138773, 0.6953902 ,
        0.6803795 , 0.7551242 , 0.14971662, 0.8068533 , 0.9675727 ,
        0.94682086, 0.54353714, 0.54715407, 0.48426998, 0.15358555],
       dtype=float32)>,
 TensorShape([50]))

In [6]:
#One hot encoding
some_list = [0,1,2,3]

#One hot encode some list
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [7]:
#Create a list of indices
some_list = [0, 1, 2, 3] #Could be red green blue purpel
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [8]:
#Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="yo I love deep learning", off_value="I also like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deep learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'yo I love deep learning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'yo I love deep learning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'yo I love deep learning']],
      dtype=object)>

In [9]:
tf.one_hot(some_list, depth=4, on_value="x", off_value="y")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'x', b'y', b'y', b'y'],
       [b'y', b'x', b'y', b'y'],
       [b'y', b'y', b'x', b'y'],
       [b'y', b'y', b'y', b'x']], dtype=object)>

In [10]:
### Squaring log , square root
#Create a new tensors
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [11]:
#Square it
tf.square(H)


<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [12]:
#Find the square root
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [13]:
#Find the log
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [14]:
##Tensors and numpy
# Numpy is fundamental computing with python
#Tensorflow interacts beautifully with Numpy Arrays

#Create a tensor directly from numpy
import numpy as np
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [15]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [16]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [17]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [18]:
#Default types of each are slighthly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
#Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

In [22]:
#Finding access to GPU
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [23]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [24]:
!nvidia-smi

Fri Jan 24 02:47:42 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P0              25W /  70W |    107MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [25]:
#If you have access to CUDA enabled GPU , tensorflow will automatically use it whenever possible